server:
  port: 8080

app:
  base-url: https://admin-biserica.ro

spring:
  datasource:
    url: jdbc:sqlite:${user.home}/ChurchAdministrationPlatform/data/ministryadmin.sqlite.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  flyway:
    enabled: false
  thymeleaf:
    mode: HTML
    cache: true

theme:
  app:
    title: "Church Administration Platform (prod)"

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
